version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: new_password
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3307"  # використовуємо один і той самий порт для контейнера і хоста
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: node-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: new_password
      DB_NAME: mydb
      DB_PORT: 3306  # підключення до стандартного порту MySQL
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql_data:
